#!/usr/bin/env python3
"""Generate catalog-owned current views and validate the current-doc graph."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "docs" / "architecture" / "system-catalog.yml"
ATTESTATION_JSON = ROOT / "docs" / "governance" / "attestation-consumers.json"
ATTESTATION_MARKDOWN = ROOT / "docs" / "audits" / "attestation-consumer-inventory.md"

GENERATED_NOTICE = (
    "> Generated from `docs/architecture/system-catalog.yml`. "
    "Do not edit this section; run `task docs:generate-current-views`."
)
BEGIN = "<!-- BEGIN GENERATED: system-catalog -->"
END = "<!-- END GENERATED: system-catalog -->"
LINK_RE = re.compile(r"(?<!!)\[[^\]]*\]\(([^)]+)\)")


def load_catalog(root: Path = ROOT) -> dict[str, Any]:
    return yaml.safe_load((root / CATALOG_PATH.relative_to(ROOT)).read_text(encoding="utf-8"))


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def _short_paths(paths: list[str]) -> str:
    return "<br>".join(f"`{path}`" for path in paths)


def render_framework_systems(catalog: dict[str, Any]) -> str:
    lines = [
        BEGIN,
        GENERATED_NOTICE,
        "",
        "| System | Lifecycle | Current responsibility | Primary roots | Verification |",
        "| --- | --- | --- | --- | --- |",
    ]
    for system in catalog["systems"]:
        lines.append(
            "| "
            + " | ".join(
                (
                    _cell(system["name"]),
                    f"`{_cell(system['status'])}`",
                    _cell(system["summary"]),
                    _short_paths(system["runtime_roots"]),
                    "<br>".join(f"`{_cell(check)}`" for check in system["checks"]),
                )
            )
            + " |"
        )
    lines.extend((END, ""))
    return "\n".join(lines)


def render_module_systems(catalog: dict[str, Any]) -> str:
    lines = [
        BEGIN,
        GENERATED_NOTICE,
        "",
        "| System | Lifecycle | Runtime roots | Ownership note |",
        "| --- | --- | --- | --- |",
    ]
    for system in catalog["systems"]:
        lines.append(
            "| "
            + " | ".join(
                (
                    _cell(system["name"]),
                    f"`{_cell(system['status'])}`",
                    _short_paths(system["runtime_roots"]),
                    _cell(system["mature_posture"]),
                )
            )
            + " |"
        )
    lines.extend((END, ""))
    return "\n".join(lines)


def _replace_generated(text: str, rendered: str) -> str:
    pattern = re.compile(rf"{re.escape(BEGIN)}.*?{re.escape(END)}\n?", re.DOTALL)
    if not pattern.search(text):
        raise ValueError("generated system-catalog markers are missing")
    return pattern.sub(rendered, text, count=1)


def render_attestation_inventory(data: dict[str, Any]) -> str:
    digest = hashlib.sha256(
        json.dumps(data, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()
    summary = data["summary"]
    lines = [
        "# Attestation Consumer Inventory",
        "",
        "> Generated from `docs/governance/attestation-consumers.json`. "
        "Do not edit this file; run `task docs:generate-current-views`.",
        "",
        f"Source digest: `{digest}`",
        "",
        "## Baseline and scope",
        "",
        f"- Baseline SHA: `{data['baseline_sha']}`",
        f"- Consumers: **{summary['total_consumers']}**",
        f"- High/critical consumers: **{summary['high_or_critical_count']}**",
        f"- Exclusions: **{len(data.get('exclusions', []))}**",
        f"- Unclassified hits: **{len(data.get('unclassified_hits', []))}**",
        "- Scan roots: " + ", ".join(f"`{value}`" for value in data["scope"]["source_roots"]),
        "- Scan terms: " + ", ".join(f"`{value}`" for value in data["scope"]["scan_terms"]),
        "",
        "## Summary by role",
        "",
        "| Role | Count |",
        "| --- | ---: |",
    ]
    lines.extend(f"| `{key}` | {value} |" for key, value in sorted(summary["by_role"].items()))
    lines.extend(("", "## Summary by disposition", "", "| Disposition | Count |", "| --- | ---: |"))
    lines.extend(
        f"| `{key}` | {value} |" for key, value in sorted(summary["by_disposition"].items())
    )
    lines.extend(
        (
            "",
            "## Consumer matrix",
            "",
            "| ID | Path / symbol | Role | Semantics | Version binding | Risk | "
            "Disposition | Target owner |",
            "| --- | --- | --- | --- | --- | --- | --- | --- |",
        )
    )
    for consumer in data["consumers"]:
        path_symbol = f"`{consumer['path']}` / `{consumer['symbol']}`"
        lines.append(
            "| "
            + " | ".join(
                _cell(value)
                for value in (
                    consumer["consumer_id"],
                    path_symbol,
                    consumer["role"],
                    consumer["decision_semantics"],
                    consumer["version_binding"],
                    consumer["risk"],
                    consumer["disposition"],
                    consumer["target_owner"],
                )
            )
            + " |"
        )
    lines.extend(
        (
            "",
            "## Interpretation boundary",
            "",
            "This is a derived audit view. Classification, line ranges, exclusions, migration "
            "recommendations, and evidence remain canonical in the machine JSON. Attestation "
            "history is evidence; its existence is not a version-bound DecisionRecord or "
            "execution authority.",
            "",
        )
    )
    return "\n".join(lines)


def expected_outputs(root: Path = ROOT) -> dict[Path, str]:
    catalog = load_catalog(root)
    framework = root / "docs" / "architecture" / "framework-index.md"
    module_map = root / "docs" / "architecture" / "module-map.md"
    attestation_json = root / ATTESTATION_JSON.relative_to(ROOT)
    return {
        framework: _replace_generated(
            framework.read_text(encoding="utf-8"), render_framework_systems(catalog)
        ),
        module_map: _replace_generated(
            module_map.read_text(encoding="utf-8"), render_module_systems(catalog)
        ),
        root / ATTESTATION_MARKDOWN.relative_to(ROOT): render_attestation_inventory(
            json.loads(attestation_json.read_text(encoding="utf-8"))
        ),
    }


def _link_target(path: Path, raw_target: str, root: Path) -> Path | None:
    target = raw_target.strip().split(maxsplit=1)[0].strip("<>")
    target = target.split("#", 1)[0]
    if not target or target.startswith(("http://", "https://", "mailto:", "app://")):
        return None
    resolved = (path.parent / target).resolve()
    try:
        resolved.relative_to(root.resolve())
    except ValueError:
        return resolved
    if resolved.is_dir() and (resolved / "README.md").is_file():
        resolved /= "README.md"
    return resolved


def current_markdown_paths(root: Path = ROOT) -> tuple[Path, ...]:
    catalog = load_catalog(root)
    navigation = catalog["documentation"]["navigation"]
    historical = (
        *navigation["historical_roots"],
        *navigation.get("historical_paths", []),
    )
    queue = [root / path for path in navigation["entrypoints"]]
    seen: set[Path] = set()
    while queue:
        path = queue.pop(0).resolve()
        if path in seen or not path.is_file() or path.suffix.lower() != ".md":
            continue
        rel = path.relative_to(root.resolve()).as_posix()
        if any(rel == prefix or rel.startswith(prefix.rstrip("/") + "/") for prefix in historical):
            continue
        seen.add(path)
        for raw_target in LINK_RE.findall(path.read_text(encoding="utf-8")):
            target = _link_target(path, raw_target, root)
            if target is not None and target.suffix.lower() == ".md":
                queue.append(target)
    return tuple(sorted(seen))


def validate_navigation(root: Path = ROOT) -> list[str]:
    failures: list[str] = []
    root_resolved = root.resolve()
    for path in current_markdown_paths(root):
        for raw_target in LINK_RE.findall(path.read_text(encoding="utf-8")):
            target = _link_target(path, raw_target, root)
            if target is None:
                continue
            try:
                rel_target = target.relative_to(root_resolved)
            except ValueError:
                failures.append(
                    f"{path.relative_to(root_resolved)} links outside repo: {raw_target}"
                )
                continue
            if not target.exists():
                failures.append(
                    f"{path.relative_to(root_resolved)} links missing path {rel_target.as_posix()}"
                )
    return failures


def check(root: Path = ROOT) -> list[str]:
    failures = validate_navigation(root)
    for path, expected in expected_outputs(root).items():
        if path.read_text(encoding="utf-8") != expected:
            failures.append(
                f"{path.relative_to(root)} is stale; run task docs:generate-current-views"
            )
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        failures = check()
        if failures:
            print("FAILURES:")
            for failure in failures:
                print(f"  {failure}")
            return 1
        print(f"OK: {len(current_markdown_paths())} navigation-reachable current docs")
        return 0
    for path, content in expected_outputs().items():
        path.write_text(content, encoding="utf-8")
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
